/** AlexShop Produktdatenbank – 150 gängige Supermarkt-Artikel */
window.PRODUCT_DB = {
  categories: ["Früchte & Gemüse", "Milch & Käse", "Fleisch & Fisch", "Getreide & Beilagen", "Brot & Backwaren", "Tiefkühl", "Getränke", "Sonstiges"],
  products: [
    { name: "Tomaten", category: "Früchte & Gemüse", icon: "tomate" },
    { name: "Cherrytomaten", category: "Früchte & Gemüse", icon: "tomate" },
    { name: "Gurken", category: "Früchte & Gemüse", icon: "gurke" },
    { name: "Paprika rot", category: "Früchte & Gemüse", icon: "paprika" },
    { name: "Paprika gelb", category: "Früchte & Gemüse", icon: "paprika" },
    { name: "Zwiebeln", category: "Früchte & Gemüse", icon: "zwiebel" },
    { name: "Knoblauch", category: "Früchte & Gemüse", icon: "knoblauch" },
    { name: "Kartoffeln", category: "Früchte & Gemüse", icon: "kartoffel" },
    { name: "Karotten", category: "Früchte & Gemüse", icon: "karotte" },
    { name: "Äpfel", category: "Früchte & Gemüse", icon: "apfel" },
    { name: "Bananen", category: "Früchte & Gemüse", icon: "banane" },
    { name: "Orangen", category: "Früchte & Gemüse", icon: "orange" },
    { name: "Zitronen", category: "Früchte & Gemüse", icon: "zitrone" },
    { name: "Avocado", category: "Früchte & Gemüse", icon: "avocado" },
    { name: "Salat", category: "Früchte & Gemüse", icon: "salat" },
    { name: "Spinat", category: "Früchte & Gemüse", icon: "salat" },
    { name: "Brokkoli", category: "Früchte & Gemüse", icon: "brokkoli" },
    { name: "Champignons", category: "Früchte & Gemüse", icon: "pilz" },
    { name: "Erdbeeren", category: "Früchte & Gemüse", icon: "beere" },
    { name: "Trauben", category: "Früchte & Gemüse", icon: "traube" },
    { name: "Birnen", category: "Früchte & Gemüse", icon: "birne" },
    { name: "Zucchini", category: "Früchte & Gemüse", icon: "zucchini" },
    { name: "Aubergine", category: "Früchte & Gemüse", icon: "aubergine" },
    { name: "Lauch", category: "Früchte & Gemüse", icon: "lauch" },
    { name: "Ingwer", category: "Früchte & Gemüse", icon: "ingwer" },
    { name: "Chili", category: "Früchte & Gemüse", icon: "chili" },
    { name: "Mais", category: "Früchte & Gemüse", icon: "mais" },
    { name: "Rote Bete", category: "Früchte & Gemüse", icon: "gemuese" },
    { name: "Frühlingszwiebeln", category: "Früchte & Gemüse", icon: "lauch" },
    { name: "Kiwi", category: "Früchte & Gemüse", icon: "kiwi" },
    { name: "Milch", category: "Milch & Käse", icon: "milch" },
    { name: "Hafermilch", category: "Milch & Käse", icon: "milch" },
    { name: "Joghurt natur", category: "Milch & Käse", icon: "joghurt" },
    { name: "Griechischer Joghurt", category: "Milch & Käse", icon: "joghurt" },
    { name: "Butter", category: "Milch & Käse", icon: "butter" },
    { name: "Sahne", category: "Milch & Käse", icon: "milch" },
    { name: "Schmand", category: "Milch & Käse", icon: "milch" },
    { name: "Quark", category: "Milch & Käse", icon: "joghurt" },
    { name: "Mozzarella", category: "Milch & Käse", icon: "kaese" },
    { name: "Parmesan", category: "Milch & Käse", icon: "kaese" },
    { name: "Gouda", category: "Milch & Käse", icon: "kaese" },
    { name: "Feta", category: "Milch & Käse", icon: "kaese" },
    { name: "Emmentaler", category: "Milch & Käse", icon: "kaese" },
    { name: "Frischkäse", category: "Milch & Käse", icon: "kaese" },
    { name: "Eier", category: "Milch & Käse", icon: "ei" },
    { name: "H-Milch", category: "Milch & Käse", icon: "milch" },
    { name: "Kokosmilch", category: "Milch & Käse", icon: "milch" },
    { name: "Crème fraîche", category: "Milch & Käse", icon: "milch" },
    { name: "Schmelzkäse", category: "Milch & Käse", icon: "kaese" },
    { name: "Reibekäse", category: "Milch & Käse", icon: "kaese" },
    { name: "Hähnchenbrust", category: "Fleisch & Fisch", icon: "huhn" },
    { name: "Hähnchenfilet", category: "Fleisch & Fisch", icon: "huhn" },
    { name: "Hackfleisch", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Rindersteak", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Schweineschnitzel", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Speck", category: "Fleisch & Fisch", icon: "speck" },
    { name: "Salami", category: "Fleisch & Fisch", icon: "wurst" },
    { name: "Schinken", category: "Fleisch & Fisch", icon: "wurst" },
    { name: "Bratwurst", category: "Fleisch & Fisch", icon: "wurst" },
    { name: "Lachs", category: "Fleisch & Fisch", icon: "fisch" },
    { name: "Thunfisch", category: "Fleisch & Fisch", icon: "fisch" },
    { name: "Garnelen", category: "Fleisch & Fisch", icon: "garnelen" },
    { name: "Krevetten", category: "Fleisch & Fisch", icon: "garnelen" },
    { name: "Forelle", category: "Fleisch & Fisch", icon: "fisch" },
    { name: "Putenbrust", category: "Fleisch & Fisch", icon: "huhn" },
    { name: "Rinderhack", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Schweinehack", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Kassler", category: "Fleisch & Fisch", icon: "fleisch" },
    { name: "Fischfilet", category: "Fleisch & Fisch", icon: "fisch" },
    { name: "Reis", category: "Getreide & Beilagen", icon: "reis" },
    { name: "Basmatireis", category: "Getreide & Beilagen", icon: "reis" },
    { name: "Spaghetti", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Penne", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Fusilli", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Linsen rot", category: "Getreide & Beilagen", icon: "linsen" },
    { name: "Linsen grün", category: "Getreide & Beilagen", icon: "linsen" },
    { name: "Kichererbsen", category: "Getreide & Beilagen", icon: "linsen" },
    { name: "Bohnen", category: "Getreide & Beilagen", icon: "bohne" },
    { name: "Kidneybohnen", category: "Getreide & Beilagen", icon: "bohne" },
    { name: "Couscous", category: "Getreide & Beilagen", icon: "getreide" },
    { name: "Bulgur", category: "Getreide & Beilagen", icon: "getreide" },
    { name: "Haferflocken", category: "Getreide & Beilagen", icon: "hafer" },
    { name: "Mehl", category: "Getreide & Beilagen", icon: "mehl" },
    { name: "Polenta", category: "Getreide & Beilagen", icon: "getreide" },
    { name: "Quinoa", category: "Getreide & Beilagen", icon: "getreide" },
    { name: "Tortellini", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Lasagneplatten", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Reisnudeln", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Risotto-Reis", category: "Getreide & Beilagen", icon: "reis" },
    { name: "Vollkornnudeln", category: "Getreide & Beilagen", icon: "nudeln" },
    { name: "Maisgrieß", category: "Getreide & Beilagen", icon: "getreide" },
    { name: "Vollkornbrot", category: "Brot & Backwaren", icon: "brot" },
    { name: "Toastbrot", category: "Brot & Backwaren", icon: "brot" },
    { name: "Baguette", category: "Brot & Backwaren", icon: "brot" },
    { name: "Brötchen", category: "Brot & Backwaren", icon: "broetchen" },
    { name: "Ciabatta", category: "Brot & Backwaren", icon: "brot" },
    { name: "Knäckebrot", category: "Brot & Backwaren", icon: "brot" },
    { name: "Croissant", category: "Brot & Backwaren", icon: "gebaeck" },
    { name: "Brezel", category: "Brot & Backwaren", icon: "broetchen" },
    { name: "Tortillas", category: "Brot & Backwaren", icon: "brot" },
    { name: "Pizzateig", category: "Brot & Backwaren", icon: "brot" },
    { name: "Laugenstange", category: "Brot & Backwaren", icon: "broetchen" },
    { name: "Wraps", category: "Brot & Backwaren", icon: "brot" },
    { name: "TK-Pommes", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Spinat", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Erbsen", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Beeren", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Pizza", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Gemüse", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Fischstäbchen", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Hackbällchen", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Brokkoli", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Blattspinat", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Waffeln", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Eis", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Brot", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "TK-Himbeeren", category: "Tiefkühl", icon: "tiefkuehl" },
    { name: "Mineralwasser", category: "Getränke", icon: "wasser" },
    { name: "Sprudelwasser", category: "Getränke", icon: "wasser" },
    { name: "Apfelsaft", category: "Getränke", icon: "saft" },
    { name: "Orangensaft", category: "Getränke", icon: "saft" },
    { name: "Cola", category: "Getränke", icon: "getraenk" },
    { name: "Bier", category: "Getränke", icon: "bier" },
    { name: "Rotwein", category: "Getränke", icon: "wein" },
    { name: "Weißwein", category: "Getränke", icon: "wein" },
    { name: "Kaffee", category: "Getränke", icon: "kaffee" },
    { name: "Tee", category: "Getränke", icon: "tee" },
    { name: "Kakao", category: "Getränke", icon: "getraenk" },
    { name: "Energy Drink", category: "Getränke", icon: "getraenk" },
    { name: "Multivitaminsaft", category: "Getränke", icon: "saft" },
    { name: "Limonade", category: "Getränke", icon: "getraenk" },
    { name: "Olivenöl", category: "Sonstiges", icon: "ol" },
    { name: "Sonnenblumenöl", category: "Sonstiges", icon: "ol" },
    { name: "Essig", category: "Sonstiges", icon: "essig" },
    { name: "Salz", category: "Sonstiges", icon: "gewuerz" },
    { name: "Pfeffer", category: "Sonstiges", icon: "gewuerz" },
    { name: "Zucker", category: "Sonstiges", icon: "zucker" },
    { name: "Honig", category: "Sonstiges", icon: "honig" },
    { name: "Nüsse", category: "Sonstiges", icon: "nuss" },
    { name: "Mandeln", category: "Sonstiges", icon: "nuss" },
    { name: "Tomatenmark", category: "Sonstiges", icon: "dose" },
    { name: "Passierte Tomaten", category: "Sonstiges", icon: "dose" },
    { name: "Kokosöl", category: "Sonstiges", icon: "ol" },
    { name: "Senf", category: "Sonstiges", icon: "gewuerz" },
    { name: "Ketchup", category: "Sonstiges", icon: "dose" },
    { name: "Mayonnaise", category: "Sonstiges", icon: "dose" },
    { name: "Brühe", category: "Sonstiges", icon: "dose" },
    { name: "Sojasauce", category: "Sonstiges", icon: "dose" },
    { name: "Backpulver", category: "Sonstiges", icon: "mehl" },
    { name: "Vanillezucker", category: "Sonstiges", icon: "zucker" },
    { name: "Schokolade", category: "Sonstiges", icon: "schokolade" },
  ]
};

window.PRODUCT_ICONS = {"tomate": "<circle cx=\"12\" cy=\"13\" r=\"7\"/><path d=\"M12 6c-1.5 0-2.5-1-3-2\"/><path d=\"M12 6c1.5 0 2.5-1 3-2\"/>", "gurke": "<path d=\"M14 4c3 2 5 5 5 9a7 7 0 0 1-14 0c0-4 2-7 5-9\"/>", "paprika": "<path d=\"M12 3c-4 0-7 3-7 7 0 5 3 9 7 11 4-2 7-6 7-11 0-4-3-7-7-7z\"/>", "zwiebel": "<circle cx=\"12\" cy=\"13\" r=\"6\"/><path d=\"M8 8c1-2 2.5-3 4-3s3 1 4 3\"/>", "knoblauch": "<path d=\"M8 8c0-3 2-5 4-5s4 2 4 5v12H8V8z\"/><path d=\"M12 3v2\"/>", "kartoffel": "<ellipse cx=\"12\" cy=\"13\" rx=\"6\" ry=\"8\"/><path d=\"M9 8c0-2 1-3 3-3s3 1 3 3\"/>", "karotte": "<path d=\"M12 20l-1-8 7-5-6 13z\"/>", "apfel": "<path d=\"M12 20c-4-2-6-5-6-9a6 6 0 0 1 11-3\"/><path d=\"M12 4c0-2 1-3 2-3\"/>", "banane": "<path d=\"M4 16c2-6 6-10 12-12 0 6-2 11-6 15-2 2-4 3-6 3z\"/>", "orange": "<circle cx=\"12\" cy=\"14\" r=\"7\"/><path d=\"M12 4v3\"/>", "zitrone": "<ellipse cx=\"12\" cy=\"14\" rx=\"6\" ry=\"7\"/><path d=\"M12 4v2\"/>", "avocado": "<ellipse cx=\"12\" cy=\"14\" rx=\"7\" ry=\"8\"/><circle cx=\"12\" cy=\"15\" r=\"2\"/>", "salat": "<path d=\"M6 14c0-4 3-7 6-7s6 3 6 7\"/><path d=\"M10 17h4\"/>", "brokkoli": "<path d=\"M8 14c0-4 2-7 5-8 3 1 5 4 5 8H8z\"/><path d=\"M16 14c0-4-2-7-5-8-3 1-5 4-5 8h10z\"/>", "pilz": "<path d=\"M6 12c0-4 3-7 6-7s6 3 6 7\"/><rect x=\"9\" y=\"12\" width=\"6\" height=\"6\" rx=\"1\"/>", "beere": "<circle cx=\"8\" cy=\"14\" r=\"3\"/><circle cx=\"14\" cy=\"12\" r=\"3\"/><circle cx=\"11\" cy=\"17\" r=\"2\"/>", "traube": "<circle cx=\"8\" cy=\"12\" r=\"2\"/><circle cx=\"12\" cy=\"10\" r=\"2\"/><circle cx=\"16\" cy=\"12\" r=\"2\"/><circle cx=\"10\" cy=\"15\" r=\"2\"/><circle cx=\"14\" cy=\"15\" r=\"2\"/>", "birne": "<path d=\"M12 21c-4-2-6-6-6-10a5 5 0 0 1 9-3\"/><path d=\"M12 5c0-2 1-3 2-3\"/>", "zucchini": "<path d=\"M14 4c3 2 5 5 5 9a7 7 0 0 1-14 0c0-4 2-7 5-9\"/>", "aubergine": "<path d=\"M10 4c-2 0-4 2-4 5v10h12V9c0-3-2-5-4-5-2 0-3 1-4 3z\"/>", "lauch": "<path d=\"M10 20V8l2-4 2 4v12\"/><path d=\"M8 20h8\"/>", "ingwer": "<path d=\"M8 16c-2-4 0-8 4-10s8 2 8 6-2 8-6 10\"/>", "chili": "<path d=\"M12 3c-2 4-2 8 0 12 2-4 2-8 0-12z\"/>", "mais": "<path d=\"M8 4v16\"/><path d=\"M12 4v16\"/><path d=\"M16 4v16\"/>", "gemuese": "<path d=\"M6 14c0-4 3-7 6-7s6 3 6 7\"/>", "kiwi": "<circle cx=\"12\" cy=\"13\" r=\"7\"/><circle cx=\"12\" cy=\"13\" r=\"3\"/>", "milch": "<path d=\"M9 3h6l1 4v12a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V7l1-4z\"/>", "joghurt": "<path d=\"M8 8h8v12a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V8z\"/>", "butter": "<rect x=\"5\" y=\"8\" width=\"14\" height=\"10\" rx=\"2\"/>", "kaese": "<path d=\"M4 14l4-8h8l4 8H4z\"/><circle cx=\"10\" cy=\"12\" r=\"1\"/><circle cx=\"14\" cy=\"14\" r=\"1\"/>", "ei": "<path d=\"M12 21c-3-3-5-7-5-10a5 5 0 0 1 10 0c0 3-2 7-5 10z\"/>", "huhn": "<path d=\"M6 12c0-4 3-7 7-7 2 0 4 1 5 3\"/><circle cx=\"16\" cy=\"9\" r=\"1\"/>", "fleisch": "<path d=\"M6 12c0-4 3-7 7-7 2 0 4 1 5 3\"/><path d=\"M8 16c2 2 4 3 6 3 3 0 5-2 5-5\"/>", "speck": "<rect x=\"4\" y=\"9\" width=\"16\" height=\"6\" rx=\"1\"/><path d=\"M6 9V7h12v2\"/>", "wurst": "<path d=\"M4 12c0-3 3-5 7-5h6c3 0 5 2 5 5s-2 5-5 5H11c-4 0-7-2-7-5z\"/>", "fisch": "<path d=\"M4 12c3-4 7-6 12-6 2 4 2 8 0 12-5 0-9-2-12-6z\"/><circle cx=\"14\" cy=\"11\" r=\"1\"/>", "garnelen": "<path d=\"M4 14c2-5 6-8 11-7 4 1 7 3 7 6 0 2-2 4-4 4-2 0-4-1-6-3-1-2-2-4-4-5z\"/><path d=\"M17 9l3-2\"/><path d=\"M18 11l3 0\"/><circle cx=\"14\" cy=\"12\" r=\"1\"/>", "reis": "<path d=\"M6 12h12\"/><ellipse cx=\"12\" cy=\"12\" rx=\"7\" ry=\"3\"/>", "nudeln": "<path d=\"M4 10c2-2 4-3 6-3\"/><path d=\"M6 14c2-2 4-3 6-3\"/><path d=\"M8 18c2-2 4-3 6-3\"/>", "linsen": "<ellipse cx=\"8\" cy=\"12\" rx=\"2\" ry=\"3\"/><ellipse cx=\"12\" cy=\"11\" rx=\"2\" ry=\"3\"/><ellipse cx=\"16\" cy=\"12\" rx=\"2\" ry=\"3\"/>", "bohne": "<path d=\"M8 12c-2-4 0-8 4-8s6 4 4 8\"/>", "getreide": "<path d=\"M8 4l4 16 4-16\"/>", "hafer": "<path d=\"M6 12h12\"/><path d=\"M8 8h8\"/><path d=\"M8 16h8\"/>", "mehl": "<path d=\"M6 10h12v10H6z\"/><path d=\"M9 7h6\"/>", "brot": "<path d=\"M4 14c0-4 2-7 5-8 3-1 6 0 8 3 2 3 1 7-2 9\"/>", "broetchen": "<path d=\"M6 14c0-3 2-6 6-6s6 3 6 6\"/>", "gebaeck": "<path d=\"M6 16c0-4 2-7 6-7s6 3 6 7\"/>", "tiefkuehl": "<path d=\"M12 2v20M2 12h20M5 5l14 14M19 5L5 19\"/>", "wasser": "<path d=\"M12 3c-3 5-6 9-6 13a6 6 0 0 0 12 0c0-4-3-8-6-13z\"/>", "saft": "<rect x=\"7\" y=\"4\" width=\"10\" height=\"16\" rx=\"2\"/><path d=\"M9 8h6\"/>", "getraenk": "<path d=\"M8 4h8v16H8z\"/><path d=\"M10 8h4\"/>", "bier": "<path d=\"M7 4h8v14a3 3 0 0 1-6 0V4z\"/><path d=\"M15 7h2v5h-2\"/>", "wein": "<path d=\"M8 4h8l-2 16H10L8 4z\"/>", "kaffee": "<path d=\"M6 8h12v8a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8z\"/><path d=\"M18 10h1a2 2 0 0 1 0 4h-1\"/>", "tee": "<path d=\"M6 10h12v6a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4v-6z\"/><path d=\"M8 6h8\"/>", "ol": "<path d=\"M12 3c-3 3-5 7-5 10a5 5 0 0 0 10 0c0-3-2-7-5-10z\"/>", "essig": "<path d=\"M9 3h6l1 18H8L9 3z\"/>", "gewuerz": "<path d=\"M12 3c-2 3-3 6-3 9a3 3 0 0 0 6 0c0-3-1-6-3-9z\"/>", "zucker": "<rect x=\"6\" y=\"6\" width=\"12\" height=\"12\" rx=\"2\"/>", "honig": "<path d=\"M8 10h8v10H8z\"/><path d=\"M10 6h4v4h-4z\"/>", "nuss": "<ellipse cx=\"12\" cy=\"14\" rx=\"5\" ry=\"6\"/><path d=\"M12 8c-2 0-3 2-3 4\"/>", "dose": "<rect x=\"7\" y=\"5\" width=\"10\" height=\"14\" rx=\"1\"/><path d=\"M7 9h10\"/>", "schokolade": "<rect x=\"5\" y=\"8\" width=\"14\" height=\"8\" rx=\"1\"/><path d=\"M12 8v8\"/>", "default": "<circle cx=\"9\" cy=\"21\" r=\"1\"/><circle cx=\"20\" cy=\"21\" r=\"1\"/><path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"/>"};
